### ISSUE TITLE
SoftI2CMaster.cpp missing?

### ISSUE THREAD

**Issue by 123j4ck** [felias-fogg/SoftI2CMaster#1]
Is SoftI2CMaster.cpp available anywhere?

**Comment by q2dg** [comment]
No. All code is in .h file

**Comment by eadf** [comment]
I'm having some problems with the function definitions being in the header file. This forces me to make sure that SoftI2CMaster.h is only included once in one program. 
If I don't the linker will throw lots of "multiple definition of" errors.

For example: I would like to call ``i2c_init()`` from my ``setup()`` but I keep all of the other I²C calls in a separate C++ class. One workaround is to create a wrapper method ``MyDevice::call_i2c_init()`` but it's so contrived.

I reckon it will be in impossible to link a program that uses two c++ classes that in turn includes ``SoftI2CMaster.h``. Each of them will work fine separately, but not together in one link unit.

I've never used assembler in Arduino code, is that the reason there is no ``.c`` or ``.cpp`` file?

P.S. Thanks for the great work

**Comment by felias-fogg** [comment]
SoftI2CMaster was not meant to be included in more than one link unit. However, you can, of course, wrap a class around it. But then I don't understand, why you do not want to wrap the init call as well. For example, why not define a 'begin' method similar to how it is done in Arduino's TwoWire class?

**Comment by eadf** [comment]
I think I understand your design now. If you had put the definitions inside a .cpp file you would effectively forced the users of the library to edit the SoftI2CMaster.h file to change the pin definitions (etc.) for each application. That's a royal PITA when that happends. Specially if you have several projects each with different settings. If the Arduino IDE had a way to define global compilation directives (like any other IDE) this could have been avoided.

The downside of having the definitions in the header file is, as mentioned, that ``SoftI2CMaster.h`` can only be included once in a project. 

I didn't want to include the init call in the wrapper because it implements a cross-platform API that , by design, does not have a init/begin method. I could have put every SoftI2CMaster i2c call inside yet another wrapper but my aversion of wrappers inside wrappers kicked in :)
I think I've found a solution though, thanks to the possibility to define more than one class inside one C++ compilation unit. So I can have the two wrappers and still having a wrapper depth of one.
